spring.application.name: spring-webflux-aws-s3-v2
# AWS properties
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION:ap-southeast-1}
  s3-bucket-name: ${AWS_S3_BUCKET_NAME:your-bucket-name}
  multipart-min-part-size: 5242880 # 5MB
  endpoint: ${AWS_S3_ENDPOINT:}

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-doc

application-description: '@project.description@'
application-version: '@project.version@'
